apiVersion: apps/v1
kind: Deployment
metadata:
  name: single-key
  labels:
    app: single-key
spec:
  replicas: 100
  selector:
    matchLabels:
      app: single-key
  template:
    metadata:
      labels:
        app: single-key
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: node.kubernetes.io/instance-type
                  operator: In
                  values:
                  - m5zn.6xlarge
      containers:
      - name: single-key
        image: 592446325190.dkr.ecr.ap-northeast-2.amazonaws.com/ddb-single-key
        env:
        - name: DDB_NAME
          value: single
        resources:
          requests:
            memory: "50Mi"
            cpu: "200m"
