apiVersion: apps/v1
kind: Deployment
metadata:
  name: bursting
  labels:
    app: bursting
spec:
  replicas: 11
  selector:
    matchLabels:
      app: bursting
  template:
    metadata:
      labels:
        app: bursting
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: node.kubernetes.io/instance-type
                  operator: In
                  values:
                  - m5zn.6xlarge
      containers:
      - name: bursting
        image: 592446325190.dkr.ecr.ap-northeast-2.amazonaws.com/ddb-sort-key 
        env:
        - name: DDB_NAME
          value: bursting
        resources:
          requests:
            memory: "50Mi"
            cpu: "200m"
