apiVersion: apps/v1
kind: Deployment
metadata:
  name: p1000
  labels:
    app: p1000
spec:
  replicas: 100
  selector:
    matchLabels:
      app: p1000
  template:
    metadata:
      labels:
        app: p1000
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: node.kubernetes.io/instance-type
                  operator: In
                  values:
                  - m5zn.6xlarge
      containers:
      - name: p1000
        image: 592446325190.dkr.ecr.ap-northeast-2.amazonaws.com/ddb-sort-key
        env:
        - name: DDB_NAME
          value: p1000
        resources:
          requests:
            memory: "50Mi"
            cpu: "200m"
